CREATE TABLE `direction_models` (
	`id` integer PRIMARY KEY NOT NULL,
	`status` text DEFAULT 'COLLECTING' NOT NULL,
	`trained_at` integer NOT NULL,
	`horizon_seconds` integer DEFAULT 10 NOT NULL,
	`snapshot_count` integer DEFAULT 0 NOT NULL,
	`example_count` integer DEFAULT 0 NOT NULL,
	`market_count` integer DEFAULT 0 NOT NULL,
	`train_count` integer DEFAULT 0 NOT NULL,
	`test_count` integer DEFAULT 0 NOT NULL,
	`positive_rate` real,
	`baseline_accuracy` real,
	`accuracy` real,
	`balanced_accuracy` real,
	`precision` real,
	`recall` real,
	`auc` real,
	`log_loss` real,
	`threshold` real DEFAULT 0.5 NOT NULL,
	`feature_names` text,
	`means` text,
	`scales` text,
	`weights` text,
	`bias` real,
	`l2` real,
	`message` text NOT NULL
);
